name: flutter_iris
description: "Aplicativo para análise de íris usando IA."
publish_to: 'none' 
version: 1.0.9-beta

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies: 
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  tflite_flutter: ^0.11.0
  permission_handler: ^11.4.0
  camera: ^0.11.1
  logger: ^2.5.0  # Ou a versão mais recente
  google_fonts: ^6.2.1
  async: ^2.13.0
  camera_avfoundation: ^0.9.18+9
  material_color_utilities: ^0.11.0 
  permission_handler_android: ^12.1.0
  path_provider: ^2.1.2
  image: ^4.1.7 
  google_ml_kit: ^0.20.0

dev_dependencies:
  flutter_lints: ^5.0.0  # Certifique-se de usar a versão mais recente


flutter:
  uses-material-design: true
  assets:
    - assets/IrisImagemInstrucional.jpg  # Adicionando a imagem ao projeto
